{{- if and .Values.ingress.enabled .Values.certificates.enabled -}}
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "bitwarden.fullname" . }}-nginx
  labels:
    app.kubernetes.io/name: {{ include "bitwarden.name" . }}
    helm.sh/chart: {{ include "bitwarden.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: nginx
spec:
  secretName: {{ include "bitwarden.fullname" . }}-nginx-tls
  issuerRef:
    name: {{ .Values.certificates.issuer }}
    kind: {{ .Values.certificates.kind }}
  dnsNames:
    - {{ .Values.global.host | quote }}
{{- end -}}
